package org.contourdynamics.deskvantage.Entities;

// Generated May 16, 2016 12:41:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BpContactAccount generated by hbm2java
 */
@Entity
@Table(name = "BP_ContactAccount", catalog = "deskvantage")
public class BpContactAccount implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private StatusCode statusCode;
	private String description;
	private String accountId;
	private String extensions;
	private BpMain bpMain;

	public BpContactAccount() {
	}

	public BpContactAccount(StatusCode statusCode,
			 String description,
			String accountId, String extensions,BpMain bpMain) {
		this.statusCode = statusCode;
		this.description = description;
		this.accountId = accountId;
		this.extensions = extensions;
		this.bpMain = bpMain;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BP_MAIN")
	public BpMain getBpMain() {
		return this.bpMain;
	}

	public void setBpMain(BpMain bpMain) {
		this.bpMain = bpMain;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Status")
	public StatusCode getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "AccountID")
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "Extensions", length = 45)
	public String getExtensions() {
		return this.extensions;
	}

	public void setExtensions(String extensions) {
		this.extensions = extensions;
	}

}
