package org.contourdynamics.deskvantage.Entities;

// Generated May 16, 2016 12:41:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BpIndv generated by hbm2java
 */
@Entity
@Table(name = "BP_INDV", catalog = "deskvantage")
public class BpIndv implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private BpMain bpMain;
	private GenderCode genderCode;
	private TitleCode titleCode;
	private String firstname;
	private String middlename;
	private String lastname;
	private Date dateofbirth;

	public BpIndv() {
	}

	public BpIndv(BpMain bpMain, GenderCode genderCode, TitleCode titleCode,
			String firstname, String middlename, String lastname,
			Date dateofbirth) {
		this.bpMain = bpMain;
		this.genderCode = genderCode;
		this.titleCode = titleCode;
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.dateofbirth = dateofbirth;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BP_MAIN")
	public BpMain getBpMain() {
		return this.bpMain;
	}

	public void setBpMain(BpMain bpMain) {
		this.bpMain = bpMain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gender")
	public GenderCode getGenderCode() {
		return this.genderCode;
	}

	public void setGenderCode(GenderCode genderCode) {
		this.genderCode = genderCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "title")
	public TitleCode getTitleCode() {
		return this.titleCode;
	}

	public void setTitleCode(TitleCode titleCode) {
		this.titleCode = titleCode;
	}

	@Column(name = "firstname", length = 45)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "middlename", length = 45)
	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	@Column(name = "lastname", length = 45)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateofbirth", length = 10)
	public Date getDateofbirth() {
		return this.dateofbirth;
	}

	public void setDateofbirth(Date dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

}
