package org.contourdynamics.deskvantage.Entities;

// Generated May 16, 2016 12:41:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BpRlspWtcnPrtl generated by hbm2java
 */
@Entity
@Table(name = "BP_RLSP_WTCN_PRTL", catalog = "deskvantage")
public class BpRlspWtcnPrtl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private StatusCode statusCode;
	private BpSysUser bpSysUser;
	private BpRlsp bpRlsp;

	public BpRlspWtcnPrtl() {
	}

	public BpRlspWtcnPrtl(StatusCode statusCode, BpSysUser bpSysUser,
			BpRlsp bpRlsp) {
		this.statusCode = statusCode;
		this.bpSysUser = bpSysUser;
		this.bpRlsp = bpRlsp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STUS_CODE")
	public StatusCode getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BP_SYS_USER")
	public BpSysUser getBpSysUser() {
		return this.bpSysUser;
	}

	public void setBpSysUser(BpSysUser bpSysUser) {
		this.bpSysUser = bpSysUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BP_RLSP")
	public BpRlsp getBpRlsp() {
		return this.bpRlsp;
	}

	public void setBpRlsp(BpRlsp bpRlsp) {
		this.bpRlsp = bpRlsp;
	}

}
