package org.contourdynamics.deskvantage.Entities;

// Generated May 16, 2016 12:41:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BpRlsp generated by hbm2java
 */
@Entity
@Table(name = "BP_RLSP", catalog = "deskvantage")
public class BpRlsp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private StatusCode statusCode;
	private BpMain bpMainByPBpmain;
	private BpMain bpMainBySBpmain;
	private RlspCode rlspCode;
	private Set<BpRlspWtcnPrtl> bpRlspWtcnPrtls = new HashSet<BpRlspWtcnPrtl>(0);
	private Set<BpRlspGrupDtel> bpRlspGrupDtels = new HashSet<BpRlspGrupDtel>(0);

	public BpRlsp() {
	}

	public BpRlsp(StatusCode statusCode, BpMain bpMainByPBpmain,
			BpMain bpMainBySBpmain, RlspCode rlspCode,
			Set<BpRlspWtcnPrtl> bpRlspWtcnPrtls,
			Set<BpRlspGrupDtel> bpRlspGrupDtels) {
		this.statusCode = statusCode;
		this.bpMainByPBpmain = bpMainByPBpmain;
		this.bpMainBySBpmain = bpMainBySBpmain;
		this.rlspCode = rlspCode;
		this.bpRlspWtcnPrtls = bpRlspWtcnPrtls;
		this.bpRlspGrupDtels = bpRlspGrupDtels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STUS_CODE")
	public StatusCode getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "P_BPMAIN")
	public BpMain getBpMainByPBpmain() {
		return this.bpMainByPBpmain;
	}

	public void setBpMainByPBpmain(BpMain bpMainByPBpmain) {
		this.bpMainByPBpmain = bpMainByPBpmain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "S_BPMAIN")
	public BpMain getBpMainBySBpmain() {
		return this.bpMainBySBpmain;
	}

	public void setBpMainBySBpmain(BpMain bpMainBySBpmain) {
		this.bpMainBySBpmain = bpMainBySBpmain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RLSP")
	public RlspCode getRlspCode() {
		return this.rlspCode;
	}

	public void setRlspCode(RlspCode rlspCode) {
		this.rlspCode = rlspCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bpRlsp")
	public Set<BpRlspWtcnPrtl> getBpRlspWtcnPrtls() {
		return this.bpRlspWtcnPrtls;
	}

	public void setBpRlspWtcnPrtls(Set<BpRlspWtcnPrtl> bpRlspWtcnPrtls) {
		this.bpRlspWtcnPrtls = bpRlspWtcnPrtls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bpRlsp")
	public Set<BpRlspGrupDtel> getBpRlspGrupDtels() {
		return this.bpRlspGrupDtels;
	}

	public void setBpRlspGrupDtels(Set<BpRlspGrupDtel> bpRlspGrupDtels) {
		this.bpRlspGrupDtels = bpRlspGrupDtels;
	}
}
