package org.contourdynamics.deskvantage.Entities;

// Generated May 16, 2016 12:41:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BpRlspGrupDtel generated by hbm2java
 */
@Entity
@Table(name = "BP_RLSP_GRUP_DTEL", catalog = "deskvantage")
public class BpRlspGrupDtel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private StatusCode statusCode;
	private BpRlsp bpRlsp;
	private BpRlspGrup bpRlspGrup;

	public BpRlspGrupDtel() {
	}

	public BpRlspGrupDtel(StatusCode statusCode, BpRlsp bpRlsp,
			BpRlspGrup bpRlspGrup) {
		this.statusCode = statusCode;
		this.bpRlsp = bpRlsp;
		this.bpRlspGrup = bpRlspGrup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STUS_CODE")
	public StatusCode getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RLSP")
	public BpRlsp getBpRlsp() {
		return this.bpRlsp;
	}

	public void setBpRlsp(BpRlsp bpRlsp) {
		this.bpRlsp = bpRlsp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RLSPGroup")
	public BpRlspGrup getBpRlspGrup() {
		return this.bpRlspGrup;
	}

	public void setBpRlspGrup(BpRlspGrup bpRlspGrup) {
		this.bpRlspGrup = bpRlspGrup;
	}

}
