package org.contourdynamics.deskvantage.Entities;

// Generated May 16, 2016 12:41:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BpSysUser generated by hbm2java
 */
@Entity
@Table(name = "BP_SYS_USER", catalog = "deskvantage")
public class BpSysUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Realm realm;
	private StatusCode statusCode;
	private String user;
	private Set<BpMain> bpMains = new HashSet<BpMain>(0);
	private Set<BpRlspWtcnPrtl> bpRlspWtcnPrtls = new HashSet<BpRlspWtcnPrtl>(0);
	private Set<BpSysUserDetl> bpSysUserDetls = new HashSet<BpSysUserDetl>(0);

	public BpSysUser() {
	}

	public BpSysUser(Realm realm, StatusCode statusCode, String user,
			Set<BpMain> bpMains, Set<BpRlspWtcnPrtl> bpRlspWtcnPrtls,
			Set<BpSysUserDetl> bpSysUserDetls) {
		this.realm = realm;
		this.statusCode = statusCode;
		this.user = user;
		this.bpMains = bpMains;
		this.bpRlspWtcnPrtls = bpRlspWtcnPrtls;
		this.bpSysUserDetls = bpSysUserDetls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Realm")
	public Realm getRealm() {
		return this.realm;
	}

	public void setRealm(Realm realm) {
		this.realm = realm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "StatusCode")
	public StatusCode getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "user")
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bpSysUser")
	public Set<BpMain> getBpMains() {
		return this.bpMains;
	}

	public void setBpMains(Set<BpMain> bpMains) {
		this.bpMains = bpMains;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bpSysUser")
	public Set<BpRlspWtcnPrtl> getBpRlspWtcnPrtls() {
		return this.bpRlspWtcnPrtls;
	}

	public void setBpRlspWtcnPrtls(Set<BpRlspWtcnPrtl> bpRlspWtcnPrtls) {
		this.bpRlspWtcnPrtls = bpRlspWtcnPrtls;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "bpSysUser" ,cascade = CascadeType.ALL)
	public Set<BpSysUserDetl> getBpSysUserDetls() {
		return this.bpSysUserDetls;
	}

	public void setBpSysUserDetls(Set<BpSysUserDetl> bpSysUserDetls) {
		this.bpSysUserDetls = bpSysUserDetls;
	}

}
