package org.contourdynamics.deskvantage.Entities;

// Generated May 16, 2016 12:41:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RlspCode generated by hbm2java
 */
@Entity
@Table(name = "RLSP_CODE", catalog = "deskvantage")
public class RlspCode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String description;
	private Set<BpRlsp> bpRlsps = new HashSet<BpRlsp>(0);

	public RlspCode() {
	}

	public RlspCode(String description, Set<BpRlsp> bpRlsps) {
		this.description = description;
		this.bpRlsps = bpRlsps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rlspCode")
	public Set<BpRlsp> getBpRlsps() {
		return this.bpRlsps;
	}

	public void setBpRlsps(Set<BpRlsp> bpRlsps) {
		this.bpRlsps = bpRlsps;
	}

}
